version: '3.8'

services:

  projectmanagerapi:
    build: .
    container_name: projectmanagerapi
    ports:
      - "5862:8080"
    networks:
      - projectmanagerapinetwork

networks:
  projectmanagerapinetwork:
    driver: bridge

  default:
    driver: bridge