version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - Project.Manager.Api.network

  Project.Manager.Api:
    build: .
    container_name: Project.Manager.Api
    ports:
      - "5862:80"
    depends_on:
      - sqlserver
    networks:
      - Project.Manager.Api.network

networks:
  Project.Manager.Api.network:
    driver: bridge