version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - projectmanagerapinetwork

  projectmanagerapi:
    build: .
    container_name: projectmanagerapi
    ports:
      - "5862:8080"
    depends_on:
      - sqlserver
    networks:
      - projectmanagerapinetwork

networks:
  projectmanagerapinetwork:
    driver: bridge

  default:
    driver: bridge