name: Build and Test .NET 8 Project

on:
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET 8 SDK
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./Project.Manager.Api/Project.Manager.Api.csproj

      # Build the project
      - name: Build the project
        run: dotnet build ./Project.Manager.Api/Project.Manager.Api.csproj --configuration Release --no-restore

  # Job 2: Test
  test:
    runs-on: ubuntu-latest
    needs: build # Dependência do Job de Build
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET 8 SDK
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Run tests
      - name: Run tests
        run: dotnet test ./Project.Manager.Api/Project.Manager.Api.csproj --configuration Release --no-build --verbosity normal
